insert into CLASSE (Libelle_classe) values ('at nulla suspendisse potenti');
insert into CLASSE (Libelle_classe) values ('iaculis congue');
insert into CLASSE (Libelle_classe) values ('curabitur at');
insert into CLASSE (Libelle_classe) values ('diam nam tristique tortor');
insert into CLASSE (Libelle_classe) values ('dapibus duis at velit');
insert into CLASSE (Libelle_classe) values ('donec posuere metus vitae ipsum');
insert into CLASSE (Libelle_classe) values ('dui proin leo');
insert into CLASSE (Libelle_classe) values ('fusce congue diam');
insert into CLASSE (Libelle_classe) values ('in hac habitasse platea');
insert into CLASSE (Libelle_classe) values ('a feugiat');
insert into CLASSE (Libelle_classe) values ('ut ultrices vel augue');
insert into CLASSE (Libelle_classe) values ('nec molestie sed justo');
insert into CLASSE (Libelle_classe) values ('pede posuere nonummy integer');
insert into CLASSE (Libelle_classe) values ('at velit vivamus');
insert into CLASSE (Libelle_classe) values ('turpis integer aliquet massa id');
insert into CLASSE (Libelle_classe) values ('condimentum neque');
insert into CLASSE (Libelle_classe) values ('convallis tortor');
insert into CLASSE (Libelle_classe) values ('rhoncus aliquet pulvinar');
insert into CLASSE (Libelle_classe) values ('nulla suspendisse potenti cras in');
insert into CLASSE (Libelle_classe) values ('eget tincidunt eget tempus');
insert into CLASSE (Libelle_classe) values ('varius nulla facilisi cras');
insert into CLASSE (Libelle_classe) values ('nulla sed');
insert into CLASSE (Libelle_classe) values ('vitae consectetuer eget');
insert into CLASSE (Libelle_classe) values ('eget massa tempor');
insert into CLASSE (Libelle_classe) values ('aliquet ultrices erat tortor');
insert into CLASSE (Libelle_classe) values ('velit eu est congue elementum');
insert into CLASSE (Libelle_classe) values ('scelerisque quam');
insert into CLASSE (Libelle_classe) values ('sem praesent id massa');
insert into CLASSE (Libelle_classe) values ('curae nulla dapibus dolor vel');
insert into CLASSE (Libelle_classe) values ('et magnis dis parturient');
insert into CLASSE (Libelle_classe) values ('a ipsum');
insert into CLASSE (Libelle_classe) values ('vulputate vitae nisl aenean');
insert into CLASSE (Libelle_classe) values ('euismod scelerisque quam turpis');
insert into CLASSE (Libelle_classe) values ('suspendisse potenti cras in');
insert into CLASSE (Libelle_classe) values ('vestibulum ac est lacinia');
insert into CLASSE (Libelle_classe) values ('maecenas pulvinar lobortis est');
insert into CLASSE (Libelle_classe) values ('sed nisl nunc');
insert into CLASSE (Libelle_classe) values ('mauris non ligula pellentesque');
insert into CLASSE (Libelle_classe) values ('nulla elit');
insert into CLASSE (Libelle_classe) values ('in lectus pellentesque at nulla');
insert into CLASSE (Libelle_classe) values ('pellentesque ultrices mattis odio');
insert into CLASSE (Libelle_classe) values ('orci luctus');
insert into CLASSE (Libelle_classe) values ('lacus at');
insert into CLASSE (Libelle_classe) values ('ullamcorper augue a');
insert into CLASSE (Libelle_classe) values ('donec quis');
insert into CLASSE (Libelle_classe) values ('interdum in ante');
insert into CLASSE (Libelle_classe) values ('id sapien in');
insert into CLASSE (Libelle_classe) values ('interdum in ante vestibulum ante');
insert into CLASSE (Libelle_classe) values ('bibendum imperdiet nullam');
insert into CLASSE (Libelle_classe) values ('urna ut tellus nulla ut');
insert into CLASSE (Libelle_classe) values ('proin at');
insert into CLASSE (Libelle_classe) values ('nunc rhoncus');
insert into CLASSE (Libelle_classe) values ('eget semper rutrum');
insert into CLASSE (Libelle_classe) values ('pellentesque volutpat dui');
insert into CLASSE (Libelle_classe) values ('adipiscing lorem vitae mattis');
insert into CLASSE (Libelle_classe) values ('lacus morbi sem mauris laoreet');
insert into CLASSE (Libelle_classe) values ('hac habitasse platea dictumst etiam');
insert into CLASSE (Libelle_classe) values ('faucibus cursus urna');
insert into CLASSE (Libelle_classe) values ('augue a suscipit');
insert into CLASSE (Libelle_classe) values ('mauris ullamcorper');
insert into CLASSE (Libelle_classe) values ('convallis eget eleifend luctus');
insert into CLASSE (Libelle_classe) values ('posuere cubilia');
insert into CLASSE (Libelle_classe) values ('penatibus et magnis dis');
insert into CLASSE (Libelle_classe) values ('rutrum ac lobortis vel dapibus');
insert into CLASSE (Libelle_classe) values ('elementum nullam varius nulla facilisi');
insert into CLASSE (Libelle_classe) values ('luctus et ultrices posuere cubilia');
insert into CLASSE (Libelle_classe) values ('vitae quam suspendisse potenti');
insert into CLASSE (Libelle_classe) values ('semper porta volutpat');
insert into CLASSE (Libelle_classe) values ('ante ipsum primis in faucibus');
insert into CLASSE (Libelle_classe) values ('justo morbi ut');
insert into CLASSE (Libelle_classe) values ('in leo');
insert into CLASSE (Libelle_classe) values ('justo aliquam quis turpis eget');
insert into CLASSE (Libelle_classe) values ('ac consequat');
insert into CLASSE (Libelle_classe) values ('mollis molestie lorem');
insert into CLASSE (Libelle_classe) values ('odio justo');
insert into CLASSE (Libelle_classe) values ('semper interdum mauris ullamcorper purus');
insert into CLASSE (Libelle_classe) values ('quis augue luctus tincidunt nulla');
insert into CLASSE (Libelle_classe) values ('non sodales sed tincidunt');
insert into CLASSE (Libelle_classe) values ('dui vel sem');
insert into CLASSE (Libelle_classe) values ('sociis natoque');
insert into CLASSE (Libelle_classe) values ('luctus et ultrices posuere');
insert into CLASSE (Libelle_classe) values ('ac enim in tempor turpis');
insert into CLASSE (Libelle_classe) values ('justo morbi ut');
insert into CLASSE (Libelle_classe) values ('in eleifend quam a');
insert into CLASSE (Libelle_classe) values ('quam pede lobortis ligula sit');
insert into CLASSE (Libelle_classe) values ('est donec');
insert into CLASSE (Libelle_classe) values ('iaculis justo in hac habitasse');
insert into CLASSE (Libelle_classe) values ('ut erat curabitur gravida');
insert into CLASSE (Libelle_classe) values ('nibh in quis justo');
insert into CLASSE (Libelle_classe) values ('pede justo lacinia');
insert into CLASSE (Libelle_classe) values ('augue aliquam');
insert into CLASSE (Libelle_classe) values ('nulla sed');
insert into CLASSE (Libelle_classe) values ('nulla mollis');
insert into CLASSE (Libelle_classe) values ('commodo placerat');
insert into CLASSE (Libelle_classe) values ('consequat in consequat');
insert into CLASSE (Libelle_classe) values ('quis turpis');
insert into CLASSE (Libelle_classe) values ('vitae nisi nam ultrices');
insert into CLASSE (Libelle_classe) values ('semper rutrum nulla');
insert into CLASSE (Libelle_classe) values ('in lacus curabitur at');
insert into CLASSE (Libelle_classe) values ('venenatis turpis');
insert into CLASSE (Libelle_classe) values ('augue vel');
insert into CLASSE (Libelle_classe) values ('eget vulputate ut ultrices');
insert into CLASSE (Libelle_classe) values ('convallis morbi odio');
insert into CLASSE (Libelle_classe) values ('luctus et ultrices posuere cubilia');
insert into CLASSE (Libelle_classe) values ('luctus et ultrices posuere cubilia');
insert into CLASSE (Libelle_classe) values ('lacinia nisi venenatis tristique fusce');
insert into CLASSE (Libelle_classe) values ('vel accumsan');
insert into CLASSE (Libelle_classe) values ('eros suspendisse accumsan tortor');
insert into CLASSE (Libelle_classe) values ('sit amet diam in magna');
insert into CLASSE (Libelle_classe) values ('quam sollicitudin vitae');
insert into CLASSE (Libelle_classe) values ('cras in');
insert into CLASSE (Libelle_classe) values ('placerat praesent');
insert into CLASSE (Libelle_classe) values ('imperdiet nullam orci pede');
insert into CLASSE (Libelle_classe) values ('pellentesque volutpat dui maecenas');
insert into CLASSE (Libelle_classe) values ('pede malesuada in imperdiet et');
insert into CLASSE (Libelle_classe) values ('nulla suscipit ligula');
insert into CLASSE (Libelle_classe) values ('morbi porttitor lorem');
insert into CLASSE (Libelle_classe) values ('augue aliquam erat volutpat in');
insert into CLASSE (Libelle_classe) values ('in blandit ultrices enim lorem');
insert into CLASSE (Libelle_classe) values ('nulla sed vel enim');
insert into CLASSE (Libelle_classe) values ('magna ac consequat');
insert into CLASSE (Libelle_classe) values ('in felis');
insert into CLASSE (Libelle_classe) values ('aliquam augue quam sollicitudin vitae');
insert into CLASSE (Libelle_classe) values ('in sapien iaculis congue vivamus');
insert into CLASSE (Libelle_classe) values ('eget tincidunt eget tempus');
insert into CLASSE (Libelle_classe) values ('quam fringilla rhoncus mauris');
insert into CLASSE (Libelle_classe) values ('ut blandit');
insert into CLASSE (Libelle_classe) values ('ante ipsum');
insert into CLASSE (Libelle_classe) values ('at nunc');
insert into CLASSE (Libelle_classe) values ('id lobortis convallis');
insert into CLASSE (Libelle_classe) values ('metus vitae ipsum aliquam non');
insert into CLASSE (Libelle_classe) values ('mauris ullamcorper purus sit amet');
insert into CLASSE (Libelle_classe) values ('eleifend pede');
insert into CLASSE (Libelle_classe) values ('imperdiet sapien urna');
insert into CLASSE (Libelle_classe) values ('non velit');
insert into CLASSE (Libelle_classe) values ('ac lobortis');
insert into CLASSE (Libelle_classe) values ('rhoncus aliquet pulvinar sed nisl');
insert into CLASSE (Libelle_classe) values ('id lobortis');
insert into CLASSE (Libelle_classe) values ('justo pellentesque');
insert into CLASSE (Libelle_classe) values ('sapien placerat ante');
insert into CLASSE (Libelle_classe) values ('blandit lacinia erat');
insert into CLASSE (Libelle_classe) values ('nunc rhoncus dui vel sem');
insert into CLASSE (Libelle_classe) values ('vitae ipsum aliquam non mauris');
insert into CLASSE (Libelle_classe) values ('euismod scelerisque quam turpis adipiscing');
insert into CLASSE (Libelle_classe) values ('sit amet');
insert into CLASSE (Libelle_classe) values ('sem praesent id massa');
insert into CLASSE (Libelle_classe) values ('donec dapibus duis at');
insert into CLASSE (Libelle_classe) values ('ante vel ipsum praesent');
insert into CLASSE (Libelle_classe) values ('primis in faucibus orci');
insert into CLASSE (Libelle_classe) values ('velit id pretium');
insert into CLASSE (Libelle_classe) values ('condimentum neque sapien placerat ante');
insert into CLASSE (Libelle_classe) values ('luctus et ultrices');
insert into CLASSE (Libelle_classe) values ('ipsum dolor sit');
insert into CLASSE (Libelle_classe) values ('ante vivamus tortor duis mattis');
insert into CLASSE (Libelle_classe) values ('justo in blandit ultrices');
insert into CLASSE (Libelle_classe) values ('non quam nec dui luctus');
insert into CLASSE (Libelle_classe) values ('in faucibus orci luctus et');
insert into CLASSE (Libelle_classe) values ('ipsum praesent blandit lacinia erat');
insert into CLASSE (Libelle_classe) values ('pellentesque volutpat dui maecenas tristique');
insert into CLASSE (Libelle_classe) values ('libero nam dui proin leo');
insert into CLASSE (Libelle_classe) values ('amet eleifend');
insert into CLASSE (Libelle_classe) values ('nunc nisl duis bibendum felis');
insert into CLASSE (Libelle_classe) values ('pellentesque ultrices mattis odio donec');
insert into CLASSE (Libelle_classe) values ('in magna bibendum imperdiet nullam');
insert into CLASSE (Libelle_classe) values ('volutpat dui');
insert into CLASSE (Libelle_classe) values ('ac consequat metus sapien ut');
insert into CLASSE (Libelle_classe) values ('volutpat convallis morbi odio');
insert into CLASSE (Libelle_classe) values ('massa donec dapibus duis');
insert into CLASSE (Libelle_classe) values ('interdum venenatis turpis');
insert into CLASSE (Libelle_classe) values ('vel pede');
insert into CLASSE (Libelle_classe) values ('consectetuer eget');
insert into CLASSE (Libelle_classe) values ('justo aliquam quis turpis eget');
insert into CLASSE (Libelle_classe) values ('ut nunc vestibulum ante ipsum');
insert into CLASSE (Libelle_classe) values ('vivamus metus');
insert into CLASSE (Libelle_classe) values ('porttitor pede justo');
insert into CLASSE (Libelle_classe) values ('vestibulum ante ipsum primis in');
insert into CLASSE (Libelle_classe) values ('vulputate luctus');
insert into CLASSE (Libelle_classe) values ('aenean lectus');
insert into CLASSE (Libelle_classe) values ('a odio in hac habitasse');
insert into CLASSE (Libelle_classe) values ('tristique est et tempus');
insert into CLASSE (Libelle_classe) values ('sodales sed');
insert into CLASSE (Libelle_classe) values ('sem fusce consequat');
insert into CLASSE (Libelle_classe) values ('nibh ligula nec');
insert into CLASSE (Libelle_classe) values ('vivamus metus arcu');
insert into CLASSE (Libelle_classe) values ('metus arcu');
insert into CLASSE (Libelle_classe) values ('aenean sit');
insert into CLASSE (Libelle_classe) values ('dui vel nisl duis');
insert into CLASSE (Libelle_classe) values ('fermentum justo nec condimentum');
insert into CLASSE (Libelle_classe) values ('quis libero nullam');
insert into CLASSE (Libelle_classe) values ('sit amet turpis');
insert into CLASSE (Libelle_classe) values ('in faucibus');
insert into CLASSE (Libelle_classe) values ('tempus vel pede');
insert into CLASSE (Libelle_classe) values ('nisl duis bibendum felis sed');
insert into CLASSE (Libelle_classe) values ('aenean auctor gravida');
insert into CLASSE (Libelle_classe) values ('ut nunc vestibulum ante');
insert into CLASSE (Libelle_classe) values ('primis in');
insert into CLASSE (Libelle_classe) values ('mi nulla ac');
insert into CLASSE (Libelle_classe) values ('lacinia aenean sit');
insert into CLASSE (Libelle_classe) values ('morbi non lectus');
insert into CLASSE (Libelle_classe) values ('id justo sit amet sapien');
