insert into TYPE_FLUX (libelle_typeflux) values ('iaculis diam');
insert into TYPE_FLUX (libelle_typeflux) values ('interdum eu');
insert into TYPE_FLUX (libelle_typeflux) values ('massa');
insert into TYPE_FLUX (libelle_typeflux) values ('lorem id');
insert into TYPE_FLUX (libelle_typeflux) values ('ut ultrices vel');
insert into TYPE_FLUX (libelle_typeflux) values ('dignissim vestibulum');
insert into TYPE_FLUX (libelle_typeflux) values ('justo pellentesque viverra');
insert into TYPE_FLUX (libelle_typeflux) values ('nulla');
insert into TYPE_FLUX (libelle_typeflux) values ('etiam');
insert into TYPE_FLUX (libelle_typeflux) values ('morbi');
insert into TYPE_FLUX (libelle_typeflux) values ('lorem id');
insert into TYPE_FLUX (libelle_typeflux) values ('vitae consectetuer');
insert into TYPE_FLUX (libelle_typeflux) values ('maecenas rhoncus');
insert into TYPE_FLUX (libelle_typeflux) values ('augue vel accumsan');
insert into TYPE_FLUX (libelle_typeflux) values ('nunc nisl');
insert into TYPE_FLUX (libelle_typeflux) values ('etiam faucibus');
insert into TYPE_FLUX (libelle_typeflux) values ('euismod scelerisque quam');
insert into TYPE_FLUX (libelle_typeflux) values ('mus etiam');
insert into TYPE_FLUX (libelle_typeflux) values ('est et');
insert into TYPE_FLUX (libelle_typeflux) values ('dictumst');
insert into TYPE_FLUX (libelle_typeflux) values ('morbi');
insert into TYPE_FLUX (libelle_typeflux) values ('imperdiet nullam');
insert into TYPE_FLUX (libelle_typeflux) values ('rutrum nulla nunc');
insert into TYPE_FLUX (libelle_typeflux) values ('primis in faucibus');
insert into TYPE_FLUX (libelle_typeflux) values ('nec');
