insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('bibendum imperdiet', '26/6/2020', 1031, 0, 5, 107, 25);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('nulla tempus', '12/11/2020', 1182, 0, 5, 16, 24);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('elementum', '7/8/2020', 2159, 0, 3, 29, 25);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('condimentum', '7/3/2020', 3319, 1, 2, 196, 20);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('nunc', '17/1/2020', 1928, 0, 2, 61, 18);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('orci luctus', '19/8/2020', 1734, 1, 3, 20, 5);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('purus', '14/11/2020', 1432, 0, 1, 46, 14);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('dolor vel', '26/8/2020', 86, 0, 3, 72, 25);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('nullam', '7/5/2020', 3429, 0, 2, 13, 1);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('nascetur', '11/3/2020', 1375, 0, 4, 38, 21);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('vehicula', '2/5/2020', 3099, 0, 3, 104, 14);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('porttitor lorem', '24/3/2020', 3114, 0, 2, 20, 1);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('justo', '15/11/2020', 3044, 1, 1, 172, 8);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('maecenas tincidunt', '21/11/2020', 246, 1, 4, 115, 24);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('nulla ac', '22/5/2020', 1635, 0, 3, 12, 5);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('porttitor', '12/3/2020', 2859, 1, 1, 16, 19);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('risus', '21/5/2020', 2489, 1, 3, 162, 9);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('eget massa', '22/2/2020', 1328, 0, 4, 182, 21);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('quis augue', '30/4/2020', 29, 1, 5, 114, 3);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('at dolor', '23/1/2020', 3271, 1, 5, 185, 19);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('mattis egestas', '17/10/2020', 1431, 1, 5, 53, 15);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('nisl', '10/11/2020', 2725, 0, 3, 67, 2);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('nulla ut', '14/3/2020', 986, 0, 4, 35, 6);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('a pede', '27/12/2019', 1874, 0, 3, 93, 24);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('convallis', '25/5/2020', 2654, 0, 4, 135, 18);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('volutpat quam', '1/5/2020', 3378, 1, 5, 1, 24);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('tellus', '12/2/2020', 1544, 0, 5, 18, 21);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('lectus pellentesque', '19/2/2020', 3275, 1, 1, 56, 19);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('eu', '26/11/2020', 278, 1, 2, 181, 25);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('convallis duis', '12/7/2020', 1076, 0, 2, 21, 15);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('lorem ipsum', '4/9/2020', 971, 0, 3, 191, 12);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('erat volutpat', '2/2/2020', 3074, 1, 4, 182, 19);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('mauris', '19/1/2020', 551, 0, 1, 127, 20);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('imperdiet sapien', '5/1/2020', 1720, 1, 2, 10, 7);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('sapien', '14/2/2020', 2821, 0, 2, 68, 12);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('sem fusce', '28/2/2020', 3211, 0, 3, 170, 14);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('et', '3/2/2020', 2625, 0, 1, 165, 4);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('duis', '25/12/2019', 1266, 1, 2, 56, 14);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('est', '24/2/2020', 2227, 1, 5, 150, 9);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('nisi', '11/2/2020', 272, 1, 2, 34, 3);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('aliquet', '1/9/2020', 2485, 0, 4, 92, 22);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('dui maecenas', '7/7/2020', 1215, 1, 3, 165, 1);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('semper', '25/9/2020', 490, 0, 4, 45, 15);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('turpis', '1/3/2020', 1995, 0, 3, 69, 7);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('ut', '21/10/2020', 3080, 0, 2, 200, 21);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('nisi', '26/9/2020', 2502, 1, 3, 137, 5);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('a', '16/4/2020', 992, 1, 5, 1, 16);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('in hac', '26/8/2020', 443, 1, 2, 1, 7);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('nec sem', '30/8/2020', 2264, 1, 2, 28, 17);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('quam a', '20/4/2020', 1054, 0, 4, 196, 22);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('magna', '21/9/2020', 927, 1, 2, 39, 8);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('eros suspendisse', '14/11/2020', 1267, 1, 5, 16, 2);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('etiam vel', '10/5/2020', 1401, 0, 2, 80, 18);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('tincidunt lacus', '26/11/2020', 1761, 1, 1, 123, 3);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('etiam', '8/11/2020', 1782, 0, 1, 77, 19);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('diam', '26/1/2020', 1414, 0, 1, 59, 10);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('sapien placerat', '18/3/2020', 1102, 0, 2, 194, 13);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('faucibus', '16/10/2020', 2720, 0, 1, 185, 24);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('proin', '18/2/2020', 423, 0, 5, 151, 5);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('justo nec', '25/7/2020', 2990, 1, 2, 116, 18);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('sagittis', '27/9/2020', 112, 0, 1, 155, 24);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('risus auctor', '4/4/2020', 1366, 0, 1, 28, 17);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('auctor', '24/10/2020', 58, 1, 2, 49, 8);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('ut nulla', '4/12/2019', 640, 0, 2, 65, 2);
insert into FLUX (libelle_flux, date_flux, montant_flux, prelevementeff_flux, id_evenement, id_adherent, id_typeflux) values ('vulputate luctus', '25/9/2020', 946, 0, 1, 30, 17);
